version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}

  server:
    depends_on:
      - ${MYSQL_HOST}
    image: node:alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./server-side:/home/node/app
    ports:
      - ${SERVER_SIDE_PORT_DOCKER}:${SERVER_SIDE_PORT}
    command: npm start

  client:
    image: node:alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./client-side:/home/node/app
    ports:
      - ${CLIENT_SIDE_PORT_DOCKER}:${CLIENT_SIDE_PORT}
    command: yarn start

  documentation:
    image: nginx:latest
    ports:
      - ${DOCUMENTATION_PORT_DOCKER}:80
    volumes:
        - ./docs:/docs
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

  wordpress:
    depends_on:
      - ${MYSQL_HOST}
    image: wordpress:latest
    ports:
      - ${WORDPRESS_PORT_DOCKER}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER_USERNAME}
      WORDPRESS_DB_PASSWORD: ${MYSQL_USER_PASSWORD}

  phpmyadmin:
    depends_on:
      - ${MYSQL_HOST}
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT_DOCKER}:80
    environment:
      MYSQL_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_HOST}

volumes:
    db_data:
